### PR TITLE
Nan in blackbox

### LINKED ISSUE #685: Wallet breaks if token.USD === null when accessing Tx Form for that token
If in the API request to /tokens, one of the tokens has a USD value of null (or undefined), the wallet has an uncaught error in Tx Form. We should just show -- in the fiat values instead of breaking completely.

### LINKED ISSUE #738: Unexpected prop in Exit
After click wait 10 minutes for a withdraw when the network is congestion we are showing NaN and alerting unexpected prop in Exit

### PR DESCRIPTION
**Pull request by adrifdez**
Closes #738 

### What does this PR does?

Changed the flow to check if it's available a withdraw in a few minutes

## Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Respect code style and lint
- [ ] Update documentation (if needed)

### CODE REVIEW

File: src/domain/local-storage/index.ts [hunk 1]
```diff
@@ -1,4 +1,9 @@
-import { PendingDeposit, PendingWithdraw, PendingDelayedWithdraw } from "src/domain/hermez";
+import {
+  PendingDeposit,
+  PendingWithdraw,
+  PendingDelayedWithdraw,
+  AvailableWithdraw,
```
Comment (AlbertoElias) [inline src/domain/local-storage/index.ts:5]: Maybe call it TimerWithdraw or CheckAvailabilityWithdraw to make it clear what it is. Otherwise, it could be all exits that are available to withdraw

File: src/views/shared/exit/exit.view.jsx [hunk 2]
```diff
@@ -286,18 +288,22 @@ function Exit({
...
-          if (pendingDelayedWithdrawal) {
-            const remainingTime = getDateString(pendingDelayedWithdrawal);
+          if (pendingDelayedWithdrawal || availableWithdraw) {
+            const withdraw = pendingDelayedWithdrawal || availableWithdraw;
+            const remainingTime = getDateString(withdraw, availableWithdraw);
             return (
               <div className={classes.withdraw}>
                 <div className={`${classes.withdrawInfo} ${classes.withdrawInfoDelayed}`}>
-                  {pendingDelayedWithdrawal.isInstant && (
+                  {withdraw && (
```
Comment (AlbertoElias) [inline src/views/shared/exit/exit.view.jsx:301]: This could be true if there is a pendingDelayedWithdrawal that is not instant. Might be worth checking availableWithdraw instead?

File: src/domain/local-storage/index.ts (hunk 1 above)
Comment (adrifdez) [reply src/domain/local-storage/index.ts:5]: I like TimerWithdraw

File: src/views/shared/exit/exit.view.jsx (hunk 2 above)
Comment (adrifdez) [reply src/views/shared/exit/exit.view.jsx:301]: Yes that logic doesn't have sense there

**Review by AlbertoElias — APPROVED** [review]

File: src/views/shared/exit/exit.view.jsx [hunk 3]
```diff
@@ -286,18 +289,22 @@ function Exit({
...
             (pendingDelayedWithdrawal) => pendingDelayedWithdrawal.id === exitId
           );
+          const timerWithdraw = timerWithdraws?.find(
+            (timerWithdraws) => timerWithdraws.id === exitId
+          );
 
-          if (pendingDelayedWithdrawal) {
-            const remainingTime = getDateString(pendingDelayedWithdrawal);
+          if (pendingDelayedWithdrawal || timerWithdraw) {
+            const withdraw = pendingDelayedWithdrawal || timerWithdraw;
```
Comment (amonsosanz) [inline src/views/shared/exit/exit.view.jsx:297]: For better readability, I'd move this line up and test for `withdraw` in the if condition.

File: src/views/shared/exit-list/exit-list.view.jsx [hunk 4]
```diff
@@ -69,9 +75,12 @@ ExitList.propTypes = {
   fiatExchangeRates: PropTypes.object,
   pendingWithdraws: PropTypes.array,
   pendingDelayedWithdraws: PropTypes.array,
+  timerWithdraws: PropTypes.array,
   coordinatorState: PropTypes.object,
   onAddPendingDelayedWithdraw: PropTypes.func.isRequired,
   onRemovePendingDelayedWithdraw: PropTypes.func.isRequired,
+  onAddTimerWithdraw: PropTypes.func.isRequired,
+  onRemoveTimerWithdraw: PropTypes.func.isRequired,
```
[the remark this answers is not in the document]
Comment (adrifdez) [reply src/views/shared/exit-list/exit-list.view.jsx:83]: It's provide just to one `ExitList` inside Home, I've added to both

**Comment by amonsosanz** [comment]
image

I'd increase the contrast and make the info icon be properly aligned

**Comment by amonsosanz** [comment]
image

We should add one minute or show the seconds.

**Comment by adrifdez** [comment]
> we should use the color from the theme

We change it to follow the design in zeplin image

**Comment by AlbertoElias** [comment]
@adrifdez but it should use the property in the theme instead of the string literal "white"

**Comment by adrifdez** [comment]
> > we should use the color from the theme
> 
> We've changed it to follow the design in zeplin image



> @adrifdez but it should use the property in the theme instead of the string literal "white"

uyyy trueeee

**Comment by adrifdez** [comment]
> @adrifdez but it should use the property in the theme instead of the string literal "white"

uy

**Review by AlbertoElias — APPROVED** [review]

**Review by amonsosanz — APPROVED** [review]

File: src/views/shared/exit/exit.view.jsx [hunk 5]
```diff
@@ -365,9 +372,12 @@ Exit.propTypes = {
   accountIndex: PropTypes.string,
   pendingWithdraws: PropTypes.array,
   pendingDelayedWithdraws: PropTypes.array,
+  timerWithdraws: PropTypes.array,
   coordinatorState: PropTypes.object,
   onAddPendingDelayedWithdraw: PropTypes.func.isRequired,
   onRemovePendingDelayedWithdraw: PropTypes.func.isRequired,
```
Comment (amonsosanz) [inline src/views/shared/exit/exit.view.jsx:378]: We should remove this now

**Review by AlbertoElias — DISMISSED** [review]

File: src/views/home/home.view.jsx [hunk 6]
```diff
@@ -197,21 +203,20 @@ function Home({
...
-                pendingWithdraws={accountPendingWithdraws}
-                pendingDelayedWithdraws={accountPendingDelayedWithdraws}
-                onAddPendingDelayedWithdraw={onAddPendingDelayedWithdraw}
-                onRemovePendingDelayedWithdraw={onRemovePendingDelayedWithdraw}
-                coordinatorState={coordinatorStateTask?.data}
-              />
-            ) : (
-              <></>
-            )}
+              (poolTransactionsTask.status === "reloading" && (
```
Comment (amonsosanz) [inline src/views/home/home.view.jsx:206]: This open parenthesis is not positioned correctly.

**Review by amonsosanz — APPROVED** [review]

**Review by AlbertoElias — APPROVED** [review]
