### PR TITLE
Fix Remaining Time to include hours

### LINKED ISSUE #780: Fix Remaining Time to include hours
We currently show the remaining time for a batch to be forged in minutes. We now do this every 6h, so we should show 3h and 30m for example

### PR DESCRIPTION
**Pull request by amonsosanz**
Closes #780

### What does this PR does?

Formats TX pending time as '2h and 23m' or just '23m'.

## Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Respect code style and lint
- [ ] Update documentation (if needed)

### CODE REVIEW

File: src/utils/transactions.ts [hunk 1]
```diff
@@ -60,6 +60,15 @@ function getTxPendingTime(
   return timeLeftToForgeInMinutes > 0 ? timeLeftToForgeInMinutes : 0;
 }
 
+/**
+ * Formats a number of minutes to a string as "2h and 23m" or just "23m"
+ */
+function formatMinutes(minutes: number): string {
+  const remMin = Math.round(minutes % 60);
```
Comment (adrifdez) [inline src/utils/transactions.ts:67]: I think that it's better `ceil` than `round` to not show 0 min when minutes are less than 0.5

Comment (amonsosanz) [reply src/utils/transactions.ts]: Done!

**Review by adrifdez — APPROVED** [review]

**Review by elias-garcia — APPROVED** [review]
