### PR TITLE
Get the proper type of transfer

### LINKED ISSUE #725: Transfer (at least with MATIC) not working in mainnet
When sending MATIC to a valid Hez address, in Tx Details the From and To appear as the same. And when you click send, it fails. Probably worth checking with both MATIC and other tokens and see if the refactor has fixed this. We might need to deploy MATIC in testnet.

### PR DESCRIPTION
**Pull request by adrifdez**
Closes #725 

### What does this PR does?

We get the proper type of the transfer to send properly the address in the specific field

## Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Respect code style and lint
- [ ] Update documentation (if needed)

### CODE REVIEW

File: src/hermezjs-typings.d.ts [hunk 1]
```diff
@@ -395,7 +400,8 @@ declare module "@hermeznetwork/hermezjs/src/tx-utils" {
 
   function getMaxAmountFromMinimumFee(minimumFee: ScalarValue, balance: ScalarValue): ScalarValue;
 
-  // function getTransactionType();
+  function getTransactionType(transaction: Transaction): TxType;
```
Comment (elias-garcia) [inline src/hermezjs-typings.d.ts:403]: We already have an interface for transactions which is `Tx`. I know that in this case we just need the `to` from the `Tx` interface, so I would suggest to remove this new `Transaction` interface and change this signature to:

```ts
function getTransactionType(transaction: { to: Pick<Tx, "to"> }): TxType;
```

This is going to pick the same type of the `to` field in the already existing `Tx` interface without duplicating it.

Comment (elias-garcia) [reply src/hermezjs-typings.d.ts]: Sorry @adrifdez, forgot about it's holiday in your city today. I'll change it and merge it.

**Review by elias-garcia — APPROVED** [review]

**Review by elias-garcia — APPROVED** [review]

**Review by amonsosanz — APPROVED** [review]
