### PR TITLE
Move all error decoding and msg extraction logic to persistence

### LINKED ISSUE #739: Canceling a deposit from Metamask shows wrong error
When you cancel a deposit from Metamask, the error shown to the user is incorrect:

### PR DESCRIPTION
**Pull request by amonsosanz**
Closes #739.

### What does this PR does?

Move all error decoding and msg extraction logic to persistence to fix a bug found when the signatures are rejected from metamask.

## Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Respect code style and lint
- [ ] Update documentation (if needed)

### CODE REVIEW

**Review by adrifdez — APPROVED** [review]

File: src/persistence/index.ts [hunk 1]
```diff
@@ -56,3 +56,29 @@ export function postCreateAccountAuthorization(
...
+// Error decoding and message extraction
+interface MessageKeyError {
+  message: string;
+}
+
+const messageKeyErrorParser: z.ZodSchema<MessageKeyError> = z.object({
+  message: z.string(),
+});
+
+export function getErrorText(error: unknown, defaultMsg?: string): string {
```
Comment (elias-garcia) [inline src/persistence/index.ts:69]: Maybe `getErrorMessage` is a better name?

**Review by elias-garcia — APPROVED** [review]

**Review by elias-garcia — APPROVED** [review]
